name: Build and Release

on:
  push:
    branches:
      - '**'
#  pull_request:
#    types:
#      - closed

jobs:

  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Increment Version
        run: |
          git fetch --tags
          git tag -l
          latestTag=$(git describe --tags --abbrev=0)
          version=${latestTag//v/}
          IFS='.' read -ra parts <<< "$version"
          major=${parts[0]}
          minor=${parts[1]}
          patch=${parts[2]}
          patch=$((patch+1))
          newTag="v$major.$minor.$patch"
          echo "::set-output name=newTag::$newTag"

      - name: Create Release
        id: create_release
        run: |
          git tag -a ${{ steps.increment_version.outputs.newTag }} -m "Release ${{ steps.increment_version.outputs.newTag }}"
          git push origin ${{ steps.increment_version.outputs.newTag }}
